;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	autopair-insert-opening
	c-electric-semi&comma
	ess-smart-comma
	evil-backward-paragraph
	evil-change
	evil-forward-char
	evil-insert
	evil-next-line-1-first-non-blank
	evil-normal-state
	evil-previous-line-first-non-blank
	org-self-insert-command
	))

(setq mc/cmds-to-run-once
      '(
	))
